from __future__ import annotations

from ..model import ConstraintKind, EntityType, Model, ObjectifiedFactType, ValueType
from ..reporting import CapabilityEntry, CapabilityReport, CapabilityStatus


SCALAR_GQL = {
    "String": "String", "Int": "Int", "Decimal": "Decimal", "Date": "Date",
    "UUID": "UUID", "Bool": "Boolean", "Timestamp": "Timestamp", "Float": "Float",
}
BUILTIN_GQL = {"String", "Int", "Float", "Boolean", "ID"}


def _hints(model: Model, owner_id: str):
    return sorted((h for h in model.field_hints.values() if h.owner_object_type_id == owner_id), key=lambda h: h.field_name)


def _value_type(model: Model, value_id: str) -> str:
    obj = model.object_types[value_id]
    assert isinstance(obj, ValueType)
    return SCALAR_GQL[obj.scalar_kind]


def _graph_type_name(model: Model, object_id: str) -> str:
    return model.object_types[object_id].name


def _effective_id_hints(model: Model, entity_id: str):
    direct = [h for h in _hints(model, entity_id) if h.identifier_component]
    if direct:
        return direct
    sup = model.supertype_of(entity_id)
    if isinstance(sup, EntityType):
        return _effective_id_hints(model, sup.id)
    return []


def emit_sdl(model: Model) -> str:
    used_scalars = {_value_type(model, v.id) for v in model.object_types.values() if isinstance(v, ValueType)}
    custom = sorted(used_scalars - BUILTIN_GQL)
    entity_names = {o.name for o in model.object_types.values() if isinstance(o, EntityType)}
    source_facts = [f for f in model.fact_types.values() if f.id not in model.field_hints]
    projected_fact_names = {
        (model.objectification_for_fact(f.id).name if model.objectification_for_fact(f.id) is not None else f.name)
        for f in source_facts
    }
    collisions = (entity_names & projected_fact_names) | (entity_names & set(custom)) | (projected_fact_names & set(custom))
    if collisions:
        raise ValueError(f"GraphQL type/scalar name collision: {sorted(collisions)}")
    lines = ['"""Generated by factgraph. This SDL is an API/type projection, not a persistence schema."""']
    if custom:
        lines.append("")
        lines.extend(f"scalar {name}" for name in custom)
    lines.append("")

    entities = sorted((o for o in model.object_types.values() if isinstance(o, EntityType)), key=lambda o: o.name)
    for entity in entities:
        sup = model.supertype_of(entity.id)
        if isinstance(sup, EntityType):
            lines.append(f'"""Semantic subtype of {sup.name}; GraphQL SDL does not enforce population inclusion."""')
        lines.append(f"type {entity.name} {{")
        hints = _hints(model, entity.id)
        inherited_ids = _effective_id_hints(model, entity.id) if sup is not None else []
        emitted: set[str] = set()
        if not hints and not inherited_ids:
            lines.append("  id: ID!")
            emitted.add("id")
        for h in inherited_ids:
            if h.field_name in emitted or any(x.field_name == h.field_name for x in hints):
                continue
            gql = _value_type(model, h.value_type_id)
            lines.append(f"  {h.field_name}: {gql}!")
            emitted.add(h.field_name)
        for h in hints:
            gql = _value_type(model, h.value_type_id)
            bang = "!" if h.required else ""
            lines.append(f"  {h.field_name}: {gql}{bang}")
            emitted.add(h.field_name)
        lines.append("}")
        lines.append("")

    for fact in sorted(source_facts, key=lambda f: f.name):
        obj = model.objectification_for_fact(fact.id)
        type_name = obj.name if obj is not None else fact.name
        lines.append(f"type {type_name} {{")
        if obj is not None:
            lines.append("  id: ID!")
        for role in sorted(fact.roles, key=lambda r: r.ordinal):
            player = model.object_types[role.player_id]
            typ = _value_type(model, player.id) if isinstance(player, ValueType) else _graph_type_name(model, player.id)
            lines.append(f"  {role.name}: {typ}!")
        if obj is not None:
            for h in _hints(model, obj.id):
                typ = _value_type(model, h.value_type_id)
                bang = "!" if h.required else ""
                lines.append(f"  {h.field_name}: {typ}{bang}")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def capability_report(model: Model) -> CapabilityReport:
    entries: list[CapabilityEntry] = []
    for fact in sorted((f for f in model.fact_types.values() if f.id not in model.field_hints), key=lambda f: f.id):
        entries.append(CapabilityEntry("fact_type_shape", fact.id, "graphql", CapabilityStatus.NATIVE_ENFORCED, "GraphQL object type with typed role fields"))
        entries.append(CapabilityEntry("fact_set_semantics", fact.id, "graphql", CapabilityStatus.REPRESENTED_NOT_ENFORCED, reason="SDL does not enforce persistence-level uniqueness of complete fact tuples"))
    for hint in sorted(model.field_hints.values(), key=lambda h: h.field_fact_id):
        entries.append(CapabilityEntry("field_projection", hint.field_fact_id, "graphql", CapabilityStatus.NATIVE_ENFORCED, "GraphQL field and nullability"))
    for c in sorted(model.constraints.values(), key=lambda c: c.id):
        if c.kind == ConstraintKind.MANDATORY and c.fact_type_id in model.field_hints:
            entries.append(CapabilityEntry("mandatory_field", c.id, "graphql", CapabilityStatus.NATIVE_ENFORCED, "non-null field type"))
        elif c.kind == ConstraintKind.UNIQUENESS and c.fact_type_id in model.field_hints:
            entries.append(CapabilityEntry("single_valued_field", c.id, "graphql", CapabilityStatus.NATIVE_ENFORCED, "field is a single value rather than a list"))
        elif c.kind == ConstraintKind.PREFERRED_IDENTIFIER:
            entries.append(CapabilityEntry("preferred_identifier", c.id, "graphql", CapabilityStatus.REPRESENTED_NOT_ENFORCED, reason="type declaration does not enforce persistence uniqueness"))
        elif c.kind == ConstraintKind.SUBTYPE:
            entries.append(CapabilityEntry("subtype", c.id, "graphql", CapabilityStatus.METADATA_ONLY, reason="canonical SDL emits a subtype description but not enforceable set-inclusion semantics"))
        elif c.kind == ConstraintKind.VALUE:
            entries.append(CapabilityEntry("value", c.id, "graphql", CapabilityStatus.REPRESENTED_NOT_ENFORCED, reason="GraphQL scalar/type declarations do not express range or enumeration constraints generically"))
        elif c.kind == ConstraintKind.FREQUENCY:
            entries.append(CapabilityEntry("frequency", c.id, "graphql", CapabilityStatus.REPRESENTED_NOT_ENFORCED, reason="SDL does not enforce population frequency constraints"))
        elif c.kind in {ConstraintKind.SUBSET, ConstraintKind.EQUALITY, ConstraintKind.EXCLUSION}:
            entries.append(CapabilityEntry(c.kind.value, c.id, "graphql", CapabilityStatus.REPRESENTED_NOT_ENFORCED, reason="SDL does not enforce cross-fact role-sequence population constraints"))
        else:
            entries.append(CapabilityEntry(c.kind.value if c.kind != ConstraintKind.RING else f"ring:{c.ring_kind}", c.id, "graphql", CapabilityStatus.REPRESENTED_NOT_ENFORCED, reason="GraphQL SDL does not enforce population-level relational constraints"))
    for reading in model.readings.values():
        if reading.fact_type_id not in model.field_hints:
            entries.append(CapabilityEntry("reading", reading.id, "graphql", CapabilityStatus.METADATA_ONLY, reason="not represented in canonical SDL"))
    return CapabilityReport("graphql", entries)
