import pytest

from factgraph.normalize import normalize_model
from factgraph.parser import parse_model
from factgraph.sqltext import split_sql
from factgraph.targets import postgres


def test_semicolon_in_the_generated_header_comment_does_not_start_a_statement():
    sql = "-- generated by factgraph; deterministic canonical PostgreSQL projection\nCREATE TABLE t (x INT);\n"
    assert split_sql(sql) == ["-- generated by factgraph; deterministic canonical PostgreSQL projection\nCREATE TABLE t (x INT)"]
    # the old splitter produced a stray statement from the comment's tail
    assert [p.strip() for p in sql.split(";") if p.strip()][1].startswith("deterministic")


def test_quotes_comments_and_dollar_bodies_keep_their_semicolons():
    sql = ("INSERT INTO t (s) VALUES ('a;b'), ('it''s; fine');\n"
           'CREATE TABLE "odd;name" (x INT); /* block; /* nested; */ still */\n'
           "CREATE FUNCTION f() RETURNS int AS $body$ SELECT 1; $body$ LANGUAGE sql;\n"
           "DO $$ BEGIN PERFORM 1; END $$;")
    assert split_sql(sql) == [
        "INSERT INTO t (s) VALUES ('a;b'), ('it''s; fine')",
        'CREATE TABLE "odd;name" (x INT)',
        "/* block; /* nested; */ still */\nCREATE FUNCTION f() RETURNS int AS $body$ SELECT 1; $body$ LANGUAGE sql",
        "DO $$ BEGIN PERFORM 1; END $$",
    ]


def test_comment_only_pieces_are_dropped_and_unterminated_text_fails_loudly():
    assert split_sql("-- only a comment;\n  ;  ") == []
    with pytest.raises(ValueError):
        split_sql("INSERT INTO t VALUES ('open")


def test_every_example_schema_splits_into_create_and_alter_statements_only():
    from pathlib import Path
    root = Path(__file__).resolve().parents[1] / "examples"
    for path in sorted(root.glob("*.fg")):
        sql = postgres.emit_sql(normalize_model(parse_model(path.read_text())))
        for stmt in split_sql(sql):
            code = "\n".join(l for l in stmt.splitlines() if not l.lstrip().startswith("--")).lstrip()
            assert code.startswith(("CREATE", "ALTER", "COMMENT")), (path.name, stmt[:80])
