"""Split PostgreSQL text into statements.

A plain ``sql.split(";")`` breaks on the semicolon in factgraph's own header comment
(``-- generated by factgraph; deterministic ...``), so the live runners sent the comment's tail to the
server as a statement and no live PostgreSQL run could start. This splitter treats semicolons inside
``--`` comments, ``/* */`` comments (nested, as PostgreSQL allows), single-quoted strings (``''``
escapes), double-quoted identifiers and dollar-quoted bodies (``$$`` or ``$tag$``) as text, and drops
pieces that contain only comments and whitespace.
"""
from __future__ import annotations

import re

_DOLLAR_TAG = re.compile(r"\$[A-Za-z_][A-Za-z0-9_]*\$|\$\$")


def split_sql(sql: str) -> list[str]:
    statements: list[str] = []
    buf: list[str] = []
    has_code = False
    i, n = 0, len(sql)

    def flush() -> None:
        nonlocal has_code
        text = "".join(buf).strip()
        if has_code and text:
            statements.append(text)
        buf.clear()
        has_code = False

    while i < n:
        c = sql[i]
        if c == "-" and sql.startswith("--", i):
            end = sql.find("\n", i)
            end = n if end == -1 else end
            buf.append(sql[i:end]); i = end
        elif c == "/" and sql.startswith("/*", i):
            depth, j = 1, i + 2
            while j < n and depth:
                if sql.startswith("/*", j):
                    depth += 1; j += 2
                elif sql.startswith("*/", j):
                    depth -= 1; j += 2
                else:
                    j += 1
            if depth:
                raise ValueError("unterminated /* comment in SQL text")
            buf.append(sql[i:j]); i = j
        elif c in ("'", '"'):
            j = i + 1
            while True:
                k = sql.find(c, j)
                if k == -1:
                    raise ValueError(f"unterminated {c} quote in SQL text")
                if sql.startswith(c * 2, k):
                    j = k + 2
                    continue
                break
            buf.append(sql[i:k + 1]); has_code = True; i = k + 1
        elif c == "$" and (m := _DOLLAR_TAG.match(sql, i)):
            tag = m.group(0)
            k = sql.find(tag, m.end())
            if k == -1:
                raise ValueError(f"unterminated {tag} quote in SQL text")
            buf.append(sql[i:k + len(tag)]); has_code = True; i = k + len(tag)
        elif c == ";":
            flush(); i += 1
        else:
            if not c.isspace():
                has_code = True
            buf.append(c); i += 1
    flush()
    return statements
